// Banque de questions quiz, organisée par public + difficulté (même
// classification que les scénarios : enfants/adultes x Facile/Moyen/
// Difficile). Déclenchées quand une équipe trouve une cache liée à un
// scénario ou un trajet, pour gagner des points. Chaque question a 4
// choix, un seul correct. Pour ajouter des questions : complète le
// tableau correspondant à la case audience-difficulté ci-dessous.
const QUIZ_POINTS = { Facile: 5, Moyen: 10, Difficile: 15 };

const QUIZ_BANK = {
  "enfants-Facile": [
    { q: "Combien de pattes a une araignée ?", choices: ["6", "8", "4", "10"], correct: 1 },
    { q: "Quelle couleur obtient-on en mélangeant du bleu et du jaune ?", choices: ["Rouge", "Vert", "Orange", "Violet"], correct: 1 },
    { q: "Quel animal fait \"miaou\" ?", choices: ["Le chien", "Le chat", "La vache", "Le canard"], correct: 1 },
    { q: "Combien de jours y a-t-il dans une semaine ?", choices: ["5", "6", "7", "8"], correct: 2 },
    { q: "Combien de doigts as-tu sur une main ?", choices: ["4", "5", "6", "10"], correct: 1 },
    { q: "Quel est le contraire de \"grand\" ?", choices: ["Petit", "Rapide", "Fort", "Doux"], correct: 0 },
    { q: "Quel animal vit dans l'eau et a des nageoires ?", choices: ["Le chien", "Le poisson", "L'oiseau", "Le chat"], correct: 1 },
    { q: "Combien font 2 + 2 ?", choices: ["3", "4", "5", "6"], correct: 1 },
    { q: "Quelle saison vient juste après l'hiver ?", choices: ["L'été", "Le printemps", "L'automne", "La nuit"], correct: 1 },
    { q: "Quel fruit est jaune et allongé ?", choices: ["La pomme", "La banane", "La fraise", "Le raisin"], correct: 1 },
    { q: "Combien de roues a un vélo ?", choices: ["1", "2", "3", "4"], correct: 1 },
    { q: "Quel animal a une très longue trompe ?", choices: ["Le tigre", "L'éléphant", "Le singe", "Le lion"], correct: 1 },
    { q: "Quel est le bébé du chat ?", choices: ["Le chaton", "Le chiot", "Le poussin", "Le veau"], correct: 0 },
    { q: "Combien font 3 + 1 ?", choices: ["3", "4", "5", "6"], correct: 1 },
    { q: "Quelle est la couleur de l'herbe ?", choices: ["Bleue", "Verte", "Rouge", "Jaune"], correct: 1 },
    { q: "Quel animal a un long cou ?", choices: ["Le chat", "La girafe", "Le chien", "Le lapin"], correct: 1 },
    { q: "Combien de mois y a-t-il dans une année ?", choices: ["10", "11", "12", "13"], correct: 2 },
    { q: "Quel est le contraire de \"chaud\" ?", choices: ["Froid", "Rapide", "Grand", "Doux"], correct: 0 },
    { q: "Quel animal saute et vit près d'une mare ?", choices: ["La grenouille", "Le chat", "L'oiseau", "Le poisson"], correct: 0 },
    { q: "Quelle forme a un ballon rond ?", choices: ["Carrée", "Ronde", "Triangulaire", "Rectangulaire"], correct: 1 },
    { q: "Combien font 5 - 2 ?", choices: ["1", "2", "3", "4"], correct: 2 },
    { q: "Quel est le contraire de \"propre\" ?", choices: ["Sale", "Beau", "Grand", "Fort"], correct: 0 },
    { q: "Quel animal a des rayures noires et blanches ?", choices: ["Le zèbre", "Le cheval", "L'âne", "La vache"], correct: 0 },
    { q: "Combien de roues a une voiture ?", choices: ["2", "3", "4", "6"], correct: 2 },
    { q: "Quelle est la couleur du ciel par une journée ensoleillée ?", choices: ["Verte", "Bleue", "Rouge", "Grise"], correct: 1 },
    { q: "Lequel est le plus grand : un éléphant ou une souris ?", choices: ["L'éléphant", "La souris", "Ils sont pareils", "Aucun des deux"], correct: 0 },
    { q: "Combien de saisons y a-t-il dans une année ?", choices: ["2", "3", "4", "5"], correct: 2 },
    { q: "Quel oiseau ne peut pas voler mais nage très bien ?", choices: ["Le pingouin", "L'aigle", "Le moineau", "Le corbeau"], correct: 0 },
    { q: "Quel animal donne le lait qu'on boit habituellement ?", choices: ["La vache", "Le chat", "Le chien", "L'oiseau"], correct: 0 },
    { q: "Combien font 10 - 5 ?", choices: ["3", "4", "5", "6"], correct: 2 },
    { q: "Quel jour vient juste après lundi ?", choices: ["Dimanche", "Mardi", "Mercredi", "Vendredi"], correct: 1 },
    { q: "Quelle partie du corps sert à voir ?", choices: ["Les oreilles", "Les yeux", "Le nez", "La bouche"], correct: 1 },
    { q: "Quel fruit rouge a ses pépins à l'extérieur ?", choices: ["La pomme", "La fraise", "La banane", "L'orange"], correct: 1 },
    { q: "Combien de pattes a un chien ?", choices: ["2", "4", "6", "8"], correct: 1 },
    { q: "Quelle saison fait très froid et fait parfois neiger ?", choices: ["L'été", "L'hiver", "Le printemps", "L'automne"], correct: 1 },
    { q: "Quel est le contraire de \"jour\" ?", choices: ["Matin", "Nuit", "Soir", "Midi"], correct: 1 },
    { q: "Quel animal fait \"cocorico\" ?", choices: ["Le canard", "Le coq", "Le cochon", "Le mouton"], correct: 1 },
    { q: "Combien font 6 + 3 ?", choices: ["8", "9", "10", "11"], correct: 1 },
    { q: "Quelle couleur obtient-on en mélangeant du rouge et du blanc ?", choices: ["Rose", "Orange", "Violet", "Marron"], correct: 0 },
    { q: "Quel véhicule vole dans le ciel ?", choices: ["Le bateau", "L'avion", "Le vélo", "Le train"], correct: 1 },
  ],
  "enfants-Moyen": [
    { q: "Quelle est la capitale du Canada ?", choices: ["Toronto", "Ottawa", "Montréal", "Vancouver"], correct: 1 },
    { q: "Combien de continents y a-t-il sur Terre ?", choices: ["5", "6", "7", "8"], correct: 2 },
    { q: "Quelle est la planète la plus proche du soleil ?", choices: ["Vénus", "Mercure", "Mars", "Terre"], correct: 1 },
    { q: "Combien de côtés a un hexagone ?", choices: ["5", "6", "7", "8"], correct: 1 },
    { q: "Quel organe pompe le sang dans le corps ?", choices: ["Le cerveau", "Le cœur", "L'estomac", "Le poumon"], correct: 1 },
    { q: "Quel est le plus grand océan du monde ?", choices: ["Atlantique", "Indien", "Pacifique", "Arctique"], correct: 2 },
    { q: "Combien font 7 x 8 ?", choices: ["54", "56", "58", "64"], correct: 1 },
    { q: "Quel insecte produit du miel ?", choices: ["La fourmi", "L'abeille", "Le papillon", "La mouche"], correct: 1 },
    { q: "Quelle langue parle-t-on principalement en France ?", choices: ["L'anglais", "Le français", "L'espagnol", "L'italien"], correct: 1 },
    { q: "Combien de joueurs y a-t-il dans une équipe de soccer sur le terrain ?", choices: ["9", "10", "11", "12"], correct: 2 },
    { q: "Quel est le plus long fleuve du monde ?", choices: ["Le Nil", "L'Amazone", "Le Mississippi", "Le Danube"], correct: 0 },
    { q: "Quel est le plus grand mammifère terrestre ?", choices: ["Le rhinocéros", "L'éléphant", "La girafe", "L'hippopotame"], correct: 1 },
    { q: "Quelle est la capitale de la France ?", choices: ["Lyon", "Paris", "Marseille", "Nice"], correct: 1 },
    { q: "Combien de sens le corps humain possède-t-il généralement ?", choices: ["3", "4", "5", "6"], correct: 2 },
    { q: "Quel est le plus grand pays du monde par superficie ?", choices: ["Chine", "Canada", "Russie", "États-Unis"], correct: 2 },
    { q: "Combien font 9 x 9 ?", choices: ["72", "81", "90", "99"], correct: 1 },
    { q: "Quelle planète a un grand anneau bien visible ?", choices: ["Mars", "Saturne", "Mercure", "Vénus"], correct: 1 },
    { q: "Quel sport se joue avec une raquette et un filet ?", choices: ["Le football", "Le tennis", "Le hockey", "La natation"], correct: 1 },
    { q: "Quel est l'animal le plus rapide sur terre ?", choices: ["Le lion", "Le guépard", "Le cheval", "Le tigre"], correct: 1 },
    { q: "Combien de lettres y a-t-il dans l'alphabet français ?", choices: ["24", "25", "26", "27"], correct: 2 },
    { q: "Quel est le plus petit continent ?", choices: ["L'Europe", "L'Océanie", "L'Asie", "L'Afrique"], correct: 1 },
    { q: "Quel organe permet de respirer ?", choices: ["Le cœur", "Les poumons", "Le foie", "L'estomac"], correct: 1 },
    { q: "Combien de secondes dure une minute ?", choices: ["30", "60", "90", "100"], correct: 1 },
    { q: "Quel est le principal ingrédient du pain ?", choices: ["Le riz", "La farine", "Le sucre", "Le sel"], correct: 1 },
    { q: "Quelle est la plus grande planète du système solaire ?", choices: ["La Terre", "Jupiter", "Mars", "Vénus"], correct: 1 },
    { q: "Combien de joueurs compte une équipe de basketball sur le terrain ?", choices: ["4", "5", "6", "7"], correct: 1 },
    { q: "Quel animal hiberne pendant l'hiver ?", choices: ["Le lion", "L'ours", "Le chat", "Le chien"], correct: 1 },
    { q: "Quelle est la monnaie utilisée en France aujourd'hui ?", choices: ["Le dollar", "L'euro", "La livre", "Le franc"], correct: 1 },
    { q: "Combien de dents a un adulte en général ?", choices: ["20", "28", "32", "36"], correct: 2 },
    { q: "Quel est le nom de notre galaxie ?", choices: ["La Voie lactée", "Andromède", "Orion", "La Grande Ourse"], correct: 0 },
    { q: "Quel est le plus grand animal terrestre ?", choices: ["Le rhinocéros", "L'éléphant", "L'hippopotame", "La girafe"], correct: 1 },
    { q: "Combien de côtés a un triangle ?", choices: ["2", "3", "4", "5"], correct: 1 },
    { q: "Quel pays a la forme d'une botte ?", choices: ["L'Espagne", "L'Italie", "La Grèce", "Le Portugal"], correct: 1 },
    { q: "Quelle partie de la plante absorbe l'eau du sol ?", choices: ["La feuille", "La racine", "La fleur", "La tige"], correct: 1 },
    { q: "Combien de pattes a un insecte, en général ?", choices: ["4", "6", "8", "10"], correct: 1 },
    { q: "Quel est le sport d'hiver le plus populaire au Canada ?", choices: ["Le baseball", "Le hockey sur glace", "Le football", "Le golf"], correct: 1 },
    { q: "Quel est le plus long os du corps humain ?", choices: ["Le tibia", "Le fémur", "L'humérus", "Le radius"], correct: 1 },
    { q: "Quel instrument utilise-t-on pour observer les étoiles ?", choices: ["Le microscope", "Le télescope", "Le stéthoscope", "Le périscope"], correct: 1 },
    { q: "Quelle est la vitesse de la lumière, approximativement ?", choices: ["300 km/s", "300 000 km/s", "3 000 km/s", "30 000 km/s"], correct: 1 },
    { q: "Quel est le plus grand lac d'eau douce du monde par superficie ?", choices: ["Lac Supérieur", "Lac Baïkal", "Lac Victoria", "Lac Michigan"], correct: 0 },
  ],
  "enfants-Difficile": [
    { q: "Un train roule à 60 km/h. Combien de kilomètres parcourt-il en 2 heures ?", choices: ["90", "100", "120", "150"], correct: 2 },
    { q: "Quel est le symbole chimique de l'eau ?", choices: ["H2O", "CO2", "O2", "NaCl"], correct: 0 },
    { q: "Combien de côtés a un dodécagone ?", choices: ["10", "11", "12", "13"], correct: 2 },
    { q: "Qui a formulé la théorie de la relativité ?", choices: ["Newton", "Einstein", "Galilée", "Darwin"], correct: 1 },
    { q: "Quelle est la racine carrée de 144 ?", choices: ["10", "11", "12", "13"], correct: 2 },
    { q: "Dans quel pays se trouve la tour Eiffel ?", choices: ["Italie", "France", "Espagne", "Allemagne"], correct: 1 },
    { q: "Combien de zéros y a-t-il dans un million (1 000 000) ?", choices: ["4", "5", "6", "7"], correct: 2 },
    { q: "Quel gaz les plantes absorbent-elles pour la photosynthèse ?", choices: ["Oxygène", "Azote", "Dioxyde de carbone", "Hydrogène"], correct: 2 },
    { q: "Si on est mercredi, quel jour sera-t-on dans 10 jours ?", choices: ["Lundi", "Mardi", "Vendredi", "Samedi"], correct: 3 },
    { q: "Quel est le plus petit nombre premier ?", choices: ["0", "1", "2", "3"], correct: 2 },
    { q: "Quelle planète est surnommée la \"planète rouge\" ?", choices: ["Vénus", "Mars", "Jupiter", "Saturne"], correct: 1 },
    { q: "Environ combien de temps la lumière du soleil met-elle à atteindre la Terre ?", choices: ["8 secondes", "8 minutes", "8 heures", "8 jours"], correct: 1 },
    { q: "Combien de faces a un cube ?", choices: ["4", "6", "8", "12"], correct: 1 },
    { q: "Quel est le résultat de 15 x 4 ?", choices: ["45", "50", "60", "65"], correct: 2 },
    { q: "Quelle est la formule chimique du sel de table ?", choices: ["H2O", "NaCl", "CO2", "O2"], correct: 1 },
    { q: "En quelle année a commencé la Seconde Guerre mondiale ?", choices: ["1935", "1939", "1941", "1945"], correct: 1 },
    { q: "Quel pourcentage représente la moitié de 100 ?", choices: ["25 %", "50 %", "75 %", "100 %"], correct: 1 },
    { q: "Quelle est la vitesse du son dans l'air, environ ?", choices: ["340 m/s", "1000 m/s", "3400 m/s", "34 m/s"], correct: 0 },
    { q: "Combien de temps la Lune met-elle à faire le tour de la Terre, environ ?", choices: ["1 jour", "1 semaine", "1 mois", "1 an"], correct: 2 },
    { q: "Quel est le plus grand pays d'Afrique par superficie ?", choices: ["Nigéria", "Algérie", "Égypte", "Afrique du Sud"], correct: 1 },
    { q: "Si x + 5 = 12, que vaut x ?", choices: ["5", "6", "7", "8"], correct: 2 },
    { q: "Quelle est la couche la plus externe de la Terre ?", choices: ["Le noyau", "Le manteau", "La croûte", "L'atmosphère"], correct: 2 },
    { q: "Combien de temps la Terre met-elle pour faire une rotation complète sur elle-même ?", choices: ["12 heures", "24 heures", "365 jours", "1 mois"], correct: 1 },
    { q: "Quel savant a théorisé la gravité en observant une pomme tomber ?", choices: ["Einstein", "Newton", "Galilée", "Darwin"], correct: 1 },
    { q: "Quel est le plus grand nombre premier inférieur à 20 ?", choices: ["17", "18", "19", "20"], correct: 2 },
    { q: "Quelle est la capitale de l'Australie ?", choices: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: 2 },
    { q: "Combien de paires de chromosomes a un être humain ?", choices: ["22", "23", "24", "46"], correct: 1 },
    { q: "Quel gaz représente environ 78 % de l'atmosphère terrestre ?", choices: ["Oxygène", "Azote", "Dioxyde de carbone", "Hydrogène"], correct: 1 },
    { q: "Si un carré a un côté de 5 cm, quelle est son aire ?", choices: ["10 cm²", "20 cm²", "25 cm²", "30 cm²"], correct: 2 },
    { q: "Quel explorateur est crédité d'avoir atteint l'Amérique en 1492 ?", choices: ["Magellan", "Christophe Colomb", "Vasco de Gama", "Marco Polo"], correct: 1 },
    { q: "Quelle est l'unité de mesure de la force ?", choices: ["Le watt", "Le newton", "Le joule", "Le pascal"], correct: 1 },
    { q: "Combien de temps la lumière met-elle à traverser une pièce, en pratique ?", choices: ["Instantané", "1 seconde", "1 minute", "1 heure"], correct: 0 },
    { q: "Comment appelle-t-on la division cellulaire qui produit deux cellules identiques ?", choices: ["Méiose", "Mitose", "Fusion", "Fission"], correct: 1 },
    { q: "Quelle est la plus grande île du monde ?", choices: ["Madagascar", "Groenland", "Bornéo", "Sumatra"], correct: 1 },
    { q: "Si un cercle a un rayon r, quelle formule donne son aire ?", choices: ["πr", "πr²", "2πr", "πd"], correct: 1 },
    { q: "Quel philosophe grec a enseigné à Alexandre le Grand ?", choices: ["Socrate", "Platon", "Aristote", "Pythagore"], correct: 2 },
    { q: "Combien de faces a un icosaèdre ?", choices: ["12", "16", "20", "24"], correct: 2 },
    { q: "Quelle planète du système solaire tourne \"sur le côté\" (axe très incliné) ?", choices: ["Mars", "Uranus", "Neptune", "Vénus"], correct: 1 },
    { q: "Quel est le nom du plus grand récif corallien du monde ?", choices: ["La Grande Barrière de corail", "Le récif de Belize", "Le triangle de corail", "Le récif de Tubbataha"], correct: 0 },
    { q: "Environ combien de temps met un signal GPS pour aller d'un satellite au sol ?", choices: ["0,07 seconde", "7 secondes", "70 secondes", "7 minutes"], correct: 0 },
  ],
  "adultes-Facile": [
    { q: "Quelle est la capitale de l'Italie ?", choices: ["Milan", "Rome", "Venise", "Naples"], correct: 1 },
    { q: "En quelle année a eu lieu le premier pas sur la Lune ?", choices: ["1965", "1969", "1972", "1959"], correct: 1 },
    { q: "Combien de cordes a une guitare classique ?", choices: ["4", "5", "6", "7"], correct: 2 },
    { q: "Quel est le plus petit État du monde ?", choices: ["Monaco", "Vatican", "Luxembourg", "Malte"], correct: 1 },
    { q: "Qui a peint la Joconde ?", choices: ["Van Gogh", "Picasso", "Léonard de Vinci", "Michel-Ange"], correct: 2 },
    { q: "Quelle est la monnaie utilisée au Japon ?", choices: ["Le yuan", "Le yen", "Le won", "Le dong"], correct: 1 },
    { q: "Combien de jours compte une année bissextile ?", choices: ["364", "365", "366", "367"], correct: 2 },
    { q: "Quel est l'organe le plus étendu du corps humain ?", choices: ["Le foie", "La peau", "Le cœur", "Le cerveau"], correct: 1 },
    { q: "Quelle est la langue officielle du Brésil ?", choices: ["L'espagnol", "Le portugais", "Le français", "L'anglais"], correct: 1 },
    { q: "Combien de temps la Terre met-elle à faire le tour du soleil ?", choices: ["Un jour", "Un mois", "Une année", "Une décennie"], correct: 2 },
    { q: "Quel est le plus grand désert chaud du monde ?", choices: ["Gobi", "Sahara", "Kalahari", "Mojave"], correct: 1 },
    { q: "Quel instrument sert à mesurer la température ?", choices: ["Le baromètre", "Le thermomètre", "L'altimètre", "L'hygromètre"], correct: 1 },
    { q: "Quel plat japonais est souvent préparé avec du poisson cru ?", choices: ["Les sushis", "Les tacos", "La pizza", "Le curry"], correct: 0 },
    { q: "Quelle est la capitale de l'Espagne ?", choices: ["Barcelone", "Madrid", "Séville", "Valence"], correct: 1 },
    { q: "Combien de joueurs y a-t-il dans une équipe de volleyball sur le terrain ?", choices: ["5", "6", "7", "8"], correct: 1 },
    { q: "Quel est le plus grand pays d'Amérique du Sud ?", choices: ["Argentine", "Brésil", "Pérou", "Colombie"], correct: 1 },
    { q: "Combien d'anneaux compte le logo olympique ?", choices: ["4", "5", "6", "7"], correct: 1 },
    { q: "Quel fruit est utilisé pour faire du vin ?", choices: ["La pomme", "Le raisin", "La poire", "La cerise"], correct: 1 },
    { q: "Quelle est la langue maternelle la plus parlée au monde ?", choices: ["L'anglais", "Le mandarin", "L'espagnol", "L'hindi"], correct: 1 },
    { q: "Quel est le plus grand mammifère marin ?", choices: ["Le requin", "La baleine bleue", "Le dauphin", "Le phoque"], correct: 1 },
    { q: "Combien de temps dure généralement un long métrage ?", choices: ["30 minutes", "90 minutes", "5 heures", "10 heures"], correct: 1 },
    { q: "Quelle est la capitale du Portugal ?", choices: ["Porto", "Lisbonne", "Faro", "Braga"], correct: 1 },
    { q: "Quel sport se joue avec un \"volant\" ?", choices: ["Le tennis", "Le badminton", "Le squash", "Le ping-pong"], correct: 1 },
    { q: "Quel est l'ingrédient principal du guacamole ?", choices: ["La tomate", "L'avocat", "Le concombre", "Le poivron"], correct: 1 },
    { q: "Quelle est la plus haute chaîne de montagnes du monde ?", choices: ["Les Alpes", "L'Himalaya", "Les Andes", "Les Rocheuses"], correct: 1 },
    { q: "Combien de cases y a-t-il sur un échiquier ?", choices: ["32", "48", "64", "100"], correct: 2 },
    { q: "Quel est le nom du satellite naturel de la Terre ?", choices: ["Mars", "La Lune", "Titan", "Europe"], correct: 1 },
    { q: "Quelle boisson chaude est faite à partir de grains torréfiés ?", choices: ["Le thé", "Le café", "Le chocolat chaud", "Le lait"], correct: 1 },
    { q: "Quel pays est à l'origine de la pizza margherita ?", choices: ["La France", "L'Italie", "L'Espagne", "La Grèce"], correct: 1 },
    { q: "Combien de temps dure le temps réglementaire d'un match de soccer ?", choices: ["60 minutes", "90 minutes", "120 minutes", "45 minutes"], correct: 1 },
    { q: "Quelle est la capitale de la Grèce ?", choices: ["Athènes", "Santorin", "Corinthe", "Thessalonique"], correct: 0 },
    { q: "Quel organe des sens est principalement associé au goût ?", choices: ["Le nez", "La langue", "Les yeux", "Les oreilles"], correct: 1 },
    { q: "Quelle danse est originaire d'Argentine ?", choices: ["La salsa", "Le tango", "Le flamenco", "La valse"], correct: 1 },
    { q: "Quel est le nom de la célèbre tour penchée en Italie ?", choices: ["La tour Eiffel", "La tour de Pise", "La tour de Londres", "La tour CN"], correct: 1 },
    { q: "Combien de temps faut-il pour cuire un œuf dur classique ?", choices: ["2 minutes", "10 minutes", "30 minutes", "1 heure"], correct: 1 },
    { q: "Quel est le nom du courant marin chaud qui longe l'Atlantique ?", choices: ["Le Gulf Stream", "Le Humboldt", "Le Kuroshio", "Le Benguela"], correct: 0 },
    { q: "Quelle boisson est traditionnellement associée à l'Angleterre ?", choices: ["Le café", "Le thé", "Le cidre", "La bière"], correct: 1 },
    { q: "Quelle est la capitale de la Suisse ?", choices: ["Genève", "Zurich", "Berne", "Lausanne"], correct: 2 },
    { q: "Quel fruit tropical est jaune à l'intérieur et épineux à l'extérieur ?", choices: ["La mangue", "L'ananas", "La papaye", "Le fruit du dragon"], correct: 1 },
    { q: "Quel est le plus grand désert froid du monde ?", choices: ["Le Sahara", "L'Antarctique", "Le Gobi", "L'Arctique"], correct: 1 },
  ],
  "adultes-Moyen": [
    { q: "Quel traité a officiellement mis fin à la Première Guerre mondiale ?", choices: ["Traité de Rome", "Traité de Versailles", "Traité de Paris", "Traité de Vienne"], correct: 1 },
    { q: "Quel élément chimique a pour symbole \"Fe\" ?", choices: ["Fluor", "Fer", "Francium", "Fermium"], correct: 1 },
    { q: "Qui a composé la 9e symphonie (\"Ode à la joie\") ?", choices: ["Mozart", "Bach", "Beethoven", "Chopin"], correct: 2 },
    { q: "Quelle est la plus haute montagne du monde ?", choices: ["K2", "Everest", "Kilimandjaro", "Mont Blanc"], correct: 1 },
    { q: "En quelle année le mur de Berlin est-il tombé ?", choices: ["1987", "1989", "1991", "1993"], correct: 1 },
    { q: "Quel pays a offert la statue de la Liberté aux États-Unis ?", choices: ["Le Royaume-Uni", "L'Espagne", "La France", "L'Italie"], correct: 2 },
    { q: "Quelle est l'unité de mesure de la puissance électrique ?", choices: ["Le volt", "L'ampère", "Le watt", "L'ohm"], correct: 2 },
    { q: "Quel océan sépare l'Europe de l'Amérique du Nord ?", choices: ["Pacifique", "Atlantique", "Indien", "Arctique"], correct: 1 },
    { q: "Qui a écrit le roman \"1984\" ?", choices: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"], correct: 1 },
    { q: "Quelle planète possède les anneaux les plus visibles ?", choices: ["Jupiter", "Saturne", "Uranus", "Neptune"], correct: 1 },
    { q: "Comment appelle-t-on le passage de l'eau liquide à la vapeur ?", choices: ["Condensation", "Évaporation", "Solidification", "Fusion"], correct: 1 },
    { q: "Quelle ville est surnommée la \"Ville Lumière\" ?", choices: ["Londres", "Rome", "Paris", "New York"], correct: 2 },
    { q: "Quel empire romain a été divisé en deux en 395 ?", choices: ["L'Empire perse", "L'Empire romain", "L'Empire ottoman", "L'Empire byzantin"], correct: 1 },
    { q: "Quelle est l'unité de mesure de la fréquence ?", choices: ["Le hertz", "Le watt", "Le joule", "Le volt"], correct: 0 },
    { q: "Qui a formulé les trois lois du mouvement en physique ?", choices: ["Einstein", "Newton", "Galilée", "Kepler"], correct: 1 },
    { q: "Quel pays est séparé de l'Espagne par les Pyrénées ?", choices: ["Le Portugal", "La France", "L'Italie", "L'Andorre"], correct: 1 },
    { q: "Quelle est la capitale de l'Égypte ?", choices: ["Alexandrie", "Le Caire", "Louxor", "Gizeh"], correct: 1 },
    { q: "Quel écrivain a créé le personnage de Sherlock Holmes ?", choices: ["Agatha Christie", "Arthur Conan Doyle", "Charles Dickens", "Mark Twain"], correct: 1 },
    { q: "Quelle bataille a marqué la défaite finale de Napoléon ?", choices: ["Austerlitz", "Waterloo", "Trafalgar", "Iéna"], correct: 1 },
    { q: "Quel est l'élément chimique le plus abondant dans l'univers ?", choices: ["Oxygène", "Hydrogène", "Carbone", "Hélium"], correct: 1 },
    { q: "Quelle organisation internationale a été fondée en 1945 pour maintenir la paix ?", choices: ["L'OTAN", "L'ONU", "L'Union européenne", "Le FMI"], correct: 1 },
    { q: "Quel peintre est associé au mouvement cubiste ?", choices: ["Monet", "Picasso", "Renoir", "Degas"], correct: 1 },
    { q: "Quelle est la plus longue rivière d'Europe ?", choices: ["Le Danube", "La Volga", "Le Rhin", "La Seine"], correct: 1 },
    { q: "Quel roi de France est surnommé le \"Roi Soleil\" ?", choices: ["Louis XIV", "Louis XVI", "François Ier", "Henri IV"], correct: 0 },
    { q: "Quelle est l'unité de base de la matière selon la chimie ?", choices: ["La molécule", "L'atome", "L'électron", "Le neutron"], correct: 1 },
    { q: "Quel pays a envoyé le premier homme dans l'espace ?", choices: ["Les États-Unis", "L'URSS", "La Chine", "La France"], correct: 1 },
    { q: "Comment appelle-t-on le processus par lequel les plantes produisent leur énergie ?", choices: ["Respiration", "Photosynthèse", "Fermentation", "Digestion"], correct: 1 },
    { q: "Quelle civilisation a construit le Machu Picchu ?", choices: ["Les Aztèques", "Les Incas", "Les Mayas", "Les Olmèques"], correct: 1 },
    { q: "Quel est le plus grand désert du monde (déserts froids compris) ?", choices: ["Le Sahara", "L'Antarctique", "Le Gobi", "L'Arabie"], correct: 1 },
    { q: "Quelle est la monnaie officielle du Royaume-Uni ?", choices: ["L'euro", "La livre sterling", "Le dollar", "Le franc"], correct: 1 },
    { q: "Quel physicien a proposé la théorie de la relativité générale ?", choices: ["Newton", "Einstein", "Bohr", "Hawking"], correct: 1 },
    { q: "Quelle guerre a opposé le Nord et le Sud des États-Unis ?", choices: ["La guerre d'indépendance", "La guerre de Sécession", "La guerre hispano-américaine", "La guerre de 1812"], correct: 1 },
    { q: "Quel est le principal gaz à effet de serre produit par l'activité humaine ?", choices: ["L'oxygène", "Le dioxyde de carbone", "L'azote", "L'hydrogène"], correct: 1 },
    { q: "Quelle mer très salée est bordée par l'Égypte, Israël et la Jordanie ?", choices: ["La mer Rouge", "La mer Morte", "La mer Noire", "La mer Méditerranée"], correct: 1 },
    { q: "Quel compositeur est devenu sourd mais a continué à composer ?", choices: ["Mozart", "Beethoven", "Bach", "Vivaldi"], correct: 1 },
    { q: "Quelle est la capitale de la Russie ?", choices: ["Saint-Pétersbourg", "Moscou", "Kiev", "Minsk"], correct: 1 },
    { q: "Quel traité a établi l'Union européenne en 1993 ?", choices: ["Traité de Rome", "Traité de Maastricht", "Traité de Lisbonne", "Traité de Nice"], correct: 1 },
    { q: "Quelle planète est en moyenne la plus proche de la Terre ?", choices: ["Mars", "Vénus", "Mercure", "Jupiter"], correct: 1 },
    { q: "Quel explorateur portugais a mené la première expédition à faire le tour du monde ?", choices: ["Vasco de Gama", "Magellan", "Christophe Colomb", "Cabral"], correct: 1 },
    { q: "Quelle est l'unité de mesure de la pression atmosphérique ?", choices: ["Le pascal", "Le newton", "Le joule", "Le watt"], correct: 0 },
  ],
  "adultes-Difficile": [
    { q: "Que signifie l'acronyme \"VPN\" ?", choices: ["Virtual Private Network", "Verified Personal Node", "Virtual Protected Node", "Very Private Network"], correct: 0 },
    { q: "Quel protocole assure le chiffrement des connexions HTTPS ?", choices: ["FTP", "SSH", "TLS", "SMTP"], correct: 2 },
    { q: "Combien de bits compose un octet ?", choices: ["4", "8", "16", "32"], correct: 1 },
    { q: "Quelle attaque consiste à intercepter une communication entre deux parties à leur insu ?", choices: ["Phishing", "Man-in-the-middle", "DDoS", "Brute force"], correct: 1 },
    { q: "Quel algorithme de hachage est aujourd'hui considéré comme cassé ?", choices: ["SHA-256", "MD5", "bcrypt", "AES"], correct: 1 },
    { q: "Que signifie l'acronyme \"DNS\" ?", choices: ["Domain Name System", "Digital Network Server", "Data Node Security", "Direct Name Service"], correct: 0 },
    { q: "En cybersécurité, que désigne une faille \"zero-day\" ?", choices: ["Une sauvegarde quotidienne", "Une faille inconnue et non corrigée", "Un mot de passe expiré", "Un pare-feu désactivé"], correct: 1 },
    { q: "Quel port réseau est habituellement utilisé par HTTPS ?", choices: ["21", "80", "443", "8080"], correct: 2 },
    { q: "Comment appelle-t-on la technique qui manipule une personne pour obtenir des informations confidentielles ?", choices: ["Cryptographie", "Ingénierie sociale", "Virtualisation", "Compression"], correct: 1 },
    { q: "Qui a théorisé la machine universelle, à la base de l'informatique moderne ?", choices: ["Alan Turing", "Ada Lovelace", "Claude Shannon", "John von Neumann"], correct: 0 },
    { q: "Quel type de logiciel malveillant chiffre les fichiers d'une victime contre rançon ?", choices: ["Ver", "Ransomware", "Cheval de Troie", "Rootkit"], correct: 1 },
    { q: "Que signifie l'acronyme \"GPS\" ?", choices: ["Global Positioning System", "General Public Service", "Geo Positioning Sensor", "Global Protocol System"], correct: 0 },
    { q: "Que signifie l'acronyme \"HTTP\" ?", choices: ["HyperText Transfer Protocol", "High Transfer Text Protocol", "HyperText Transmission Process", "Host Transfer Text Protocol"], correct: 0 },
    { q: "Quel type d'attaque submerge un serveur de requêtes pour le rendre indisponible ?", choices: ["Phishing", "DDoS", "Spoofing", "Keylogging"], correct: 1 },
    { q: "Que signifie l'acronyme \"2FA\" en sécurité informatique ?", choices: ["Two-Factor Authentication", "Two-File Access", "Second Firewall Authentication", "Two-Factor Access"], correct: 0 },
    { q: "Quel protocole est utilisé pour l'envoi de courriels ?", choices: ["HTTP", "SMTP", "FTP", "SNMP"], correct: 1 },
    { q: "Quel type de logiciel se déguise en programme légitime pour tromper l'utilisateur ?", choices: ["Ver", "Cheval de Troie", "Rootkit", "Spyware"], correct: 1 },
    { q: "Que signifie l'acronyme \"IP\" dans \"adresse IP\" ?", choices: ["Internet Protocol", "Internal Process", "Information Packet", "Internet Package"], correct: 0 },
    { q: "Quel algorithme de chiffrement symétrique est aujourd'hui un standard largement utilisé ?", choices: ["DES", "AES", "RSA", "MD5"], correct: 1 },
    { q: "Que signifie l'acronyme \"OTP\" utilisé pour l'authentification ?", choices: ["One-Time Password", "Online Transfer Protocol", "Open Transport Protocol", "One-Time Protocol"], correct: 0 },
    { q: "Quel type de test évalue la sécurité d'un système en simulant une attaque réelle ?", choices: ["Audit financier", "Test de pénétration", "Test unitaire", "Test de charge"], correct: 1 },
    { q: "Que vérifie un \"CAPTCHA\" ?", choices: ["La présence d'un virus", "Qu'un humain (et non un robot) utilise le site", "La vitesse du réseau", "L'intégrité d'un fichier"], correct: 1 },
    { q: "Quel port est habituellement associé au protocole SSH ?", choices: ["21", "22", "23", "25"], correct: 1 },
    { q: "Quelle attaque consiste à essayer toutes les combinaisons possibles d'un mot de passe ?", choices: ["Phishing", "Force brute", "Ingénierie sociale", "Injection SQL"], correct: 1 },
    { q: "Que signifie l'acronyme \"SQL\" ?", choices: ["Structured Query Language", "System Query Language", "Simple Query Logic", "Structured Question Language"], correct: 0 },
    { q: "Quelle attaque exploite une faille dans une base de données via une requête malveillante ?", choices: ["XSS", "Injection SQL", "DDoS", "Phishing"], correct: 1 },
    { q: "Que signifie l'acronyme \"TOR\", réseau d'anonymisation bien connu ?", choices: ["The Onion Router", "Total Online Routing", "Trusted Open Relay", "Transfer Over Routing"], correct: 0 },
    { q: "Quel système traduit les noms de domaine en adresses IP ?", choices: ["DHCP", "DNS", "FTP", "ARP"], correct: 1 },
    { q: "Quelle norme sans fil est couramment utilisée pour le Wi-Fi ?", choices: ["Bluetooth", "802.11", "NFC", "RFID"], correct: 1 },
    { q: "Quel type de logiciel malveillant se réplique lui-même sans fichier hôte ?", choices: ["Virus", "Ver", "Cheval de Troie", "Rootkit"], correct: 1 },
    { q: "Que signifie l'acronyme \"CVE\", utilisé pour cataloguer les vulnérabilités ?", choices: ["Common Vulnerabilities and Exposures", "Cyber Vulnerability Evaluation", "Critical Vulnerability Event", "Common Virus Exposure"], correct: 0 },
    { q: "Quel scientifique est reconnu comme le père de la théorie de l'information ?", choices: ["Alan Turing", "Claude Shannon", "Norbert Wiener", "John von Neumann"], correct: 1 },
    { q: "Quelle attaque redirige un utilisateur vers un faux site imitant un site légitime ?", choices: ["Phishing", "Ransomware", "DDoS", "Keylogging"], correct: 0 },
    { q: "Que signifie l'acronyme \"URL\" ?", choices: ["Uniform Resource Locator", "Universal Resource Link", "Unified Reference Locator", "Uniform Reference Link"], correct: 0 },
    { q: "Comment appelle-t-on la technique qui cache des données dans un fichier anodin (image, audio) ?", choices: ["Cryptographie", "Stéganographie", "Compression", "Obfuscation"], correct: 1 },
    { q: "Quel type de pare-feu inspecte le contenu des paquets, pas seulement les ports ?", choices: ["Pare-feu à filtrage de paquets", "Pare-feu applicatif", "Proxy", "Antivirus"], correct: 1 },
    { q: "Que signifie l'acronyme \"IoT\" ?", choices: ["Internet of Things", "Internet of Technology", "Internal Operating Terminal", "Integration of Tools"], correct: 0 },
    { q: "Quel nom porte la faille majeure découverte dans OpenSSL en 2014 ?", choices: ["Heartbleed", "Shellshock", "Spectre", "Meltdown"], correct: 0 },
    { q: "Quelle méthode de sauvegarde garde une copie hors ligne pour se protéger des ransomwares ?", choices: ["Sauvegarde cloud", "Sauvegarde air-gapped", "Sauvegarde RAID", "Sauvegarde incrémentielle"], correct: 1 },
    { q: "Comment appelle-t-on un groupe d'appareils infectés contrôlés à distance pour lancer des attaques ?", choices: ["Un cluster", "Un botnet", "Un cloud", "Un cache"], correct: 1 },
  ],
};

function quizBucketKey(audience, difficultyLabel) {
  return `${audience}-${difficultyLabel}`;
}

// Picks up to `count` questions from the audience+difficulty bucket,
// avoiding indices already used this game (tracked in `usedMap`, keyed by
// bucket). If the bucket has been exhausted, it wraps around rather than
// blocking the game. Returns null if the bucket doesn't exist at all.
function pickQuizQuestions(audience, difficultyLabel, count, usedMap) {
  const key = quizBucketKey(audience, difficultyLabel);
  const bank = QUIZ_BANK[key];
  if (!bank || bank.length === 0) return null;

  let used = usedMap[key] || [];
  let available = bank.map((_, i) => i).filter((i) => !used.includes(i));
  if (available.length < Math.min(count, bank.length)) {
    used = [];
    available = bank.map((_, i) => i);
  }

  for (let i = available.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [available[i], available[j]] = [available[j], available[i]];
  }

  const indices = available.slice(0, Math.min(count, bank.length));
  return { key, indices, questions: indices.map((i) => bank[i]) };
}
