// Scénarios préenregistrés : chaque parcours est défini par des points
// RELATIFS (cap + distance) depuis un point de départ choisi sur place.
// Comme le calcul (Geo.destinationPoint) est purement géométrique, deux
// appareils qui démarrent le même scénario depuis le même point de départ
// obtiennent exactement les mêmes caches, sans échanger la moindre donnée
// entre eux — donc sans réseau, cellulaire ou Wi-Fi, requis.
const SCENARIOS = [
  {
    id: "kids-easy-garden",
    theme: "fairy",
    title: "Le Trésor du Jardin Enchanté",
    emoji: "🧚",
    audience: "enfants",
    difficultyLabel: "Facile",
    difficultyStars: 1,
    minAge: "5-8 ans",
    setting: "Jardin, cour ou petit parc",
    intro:
      "Les lutins du jardin ont caché leur trésor avant de s'envoler pour l'hiver. " +
      "Suis les indices pour retrouver leur cachette secrète !",
    waypoints: [
      {
        bearing: 20,
        distance: 12,
        name: "L'ombre du grand arbre",
        desc: "Un lutin a laissé une empreinte de pas ici.",
        hint: "Cherche l'endroit le plus frais du jardin, là où le soleil ne passe pas.",
        ar: "fairy",
      },
      {
        bearing: 110,
        distance: 18,
        name: "Le caillou qui rit",
        desc: "On dit que ce caillou sourit quand on le regarde de près.",
        hint: "Regarde près du sol, un objet un peu rond et un peu bizarre t'attend.",
        ar: "orb",
      },
      {
        bearing: 200,
        distance: 15,
        name: "La cachette des fleurs",
        desc: "Les fleurs les plus colorées gardent un secret.",
        hint: "Approche-toi doucement pour ne pas réveiller les petites bêtes.",
        ar: "crystal",
      },
      {
        bearing: 320,
        distance: 20,
        name: "Le trésor des lutins !",
        desc: "Bravo, tu as trouvé la cachette finale ! Une petite surprise t'attend ici.",
        hint: "C'est le dernier arrêt : regarde bien tout autour de toi.",
        ar: "key",
      },
    ],
  },
  {
    id: "kids-medium-pirates",
    theme: "pirates",
    title: "Mission Pirates au Parc",
    emoji: "🏴‍☠️",
    audience: "enfants",
    difficultyLabel: "Moyen",
    difficultyStars: 3,
    minAge: "8-11 ans",
    setting: "Parc de quartier",
    intro:
      "Le capitaine Barbe-Rouge a perdu sa carte au trésor dans le parc ! " +
      "Suivez le cap du radar comme de vrais pirates pour retrouver le butin caché en 5 étapes.",
    waypoints: [
      {
        bearing: 45,
        distance: 60,
        name: "La crique du débarquement",
        desc: "L'équipage a débarqué ici en premier.",
        hint: "Cherche un endroit dégagé, comme une plage pour un bateau.",
        ar: "coin",
      },
      {
        bearing: 130,
        distance: 90,
        name: "Le rocher du perroquet",
        desc: "Un vieux perroquet aurait surveillé cet endroit.",
        hint: "Un banc, un arbre ou un rocher fait un bon perchoir.",
        ar: "skull",
      },
      {
        bearing: 210,
        distance: 70,
        name: "Le marécage des crabes",
        desc: "Attention où vous mettez les pieds, moussaillons !",
        hint: "Reste sur le chemin si le sol est humide par ici.",
        ar: "dice",
      },
      {
        bearing: 280,
        distance: 100,
        name: "La croisée des vents",
        desc: "Quatre chemins se croisent, mais un seul mène au trésor.",
        hint: "Regarde bien le radar : la flèche ne ment jamais.",
        ar: "orb",
      },
      {
        bearing: 15,
        distance: 50,
        name: "Le coffre du capitaine !",
        desc: "Le butin de Barbe-Rouge est enfin à vous !",
        hint: "C'est ici que l'aventure se termine, matelot !",
        ar: "key",
      },
    ],
  },
  {
    id: "kids-hard-forest",
    theme: "forest",
    title: "L'Énigme de la Forêt Mystérieuse",
    emoji: "🌲",
    audience: "enfants",
    difficultyLabel: "Difficile",
    difficultyStars: 4,
    minAge: "11-14 ans",
    setting: "Forêt, grand parc ou sentier",
    intro:
      "Une légende raconte qu'un ancien gardien de la forêt a caché un objet magique. " +
      "Pour le retrouver, il faudra résoudre de petites énigmes en plus de suivre le radar.",
    waypoints: [
      {
        bearing: 350,
        distance: 120,
        name: "Le sentier du silence",
        desc: "Avance sans faire de bruit, comme un vrai explorateur.",
        hint: "Énigme : 3 arbres plus loin qu'un banc, cherche une pierre marquée.",
        ar: "ghost",
      },
      {
        bearing: 80,
        distance: 150,
        name: "Le pont des échos",
        desc: "Ici, les sons voyagent loin. Écoute bien.",
        hint: "Énigme : additionne 2 + 3, avance de ce nombre de grands pas dans le cap indiqué.",
        ar: "crystal",
      },
      {
        bearing: 160,
        distance: 180,
        name: "La clairière cachée",
        desc: "Un rayon de soleil perce toujours ici, même en plein bois.",
        hint: "Énigme : le prochain indice est caché là où l'ombre est la plus courte à midi.",
        ar: "fairy",
      },
      {
        bearing: 250,
        distance: 140,
        name: "Le rocher gravé",
        desc: "Une ancienne inscription est à moitié effacée sur une pierre.",
        hint: "Énigme : cherche un symbole en forme de spirale, il indique la direction du trésor.",
        ar: "skull",
      },
      {
        bearing: 30,
        distance: 100,
        name: "Le trésor du gardien !",
        desc: "L'objet magique de la légende est enfin retrouvé.",
        hint: "Dernier arrêt : regarde en hauteur, pas seulement au sol.",
        ar: "key",
      },
    ],
  },
  {
    id: "adults-easy-heritage",
    theme: "heritage",
    title: "Balade Rétro du Vieux Quartier",
    emoji: "🏛️",
    audience: "adultes",
    difficultyLabel: "Facile",
    difficultyStars: 2,
    minAge: "Tout public",
    setting: "Quartier historique, centre-ville",
    intro:
      "Une promenade tranquille sur le thème du patrimoine local : quatre arrêts, " +
      "quelques anecdotes fictives à imaginer sur place, et une jolie balade sans stress.",
    waypoints: [
      {
        bearing: 60,
        distance: 150,
        name: "La place de l'ancien marché",
        desc: "Autrefois, les commerçants s'y retrouvaient chaque semaine.",
        hint: "Cherche un point de repère central, comme une fontaine ou une place ouverte.",
        ar: "coin",
      },
      {
        bearing: 140,
        distance: 200,
        name: "La façade oubliée",
        desc: "Un détail architectural que peu de passants remarquent.",
        hint: "Lève les yeux : les indices sont souvent au-dessus du rez-de-chaussée.",
        ar: "crystal",
      },
      {
        bearing: 220,
        distance: 180,
        name: "Le passage discret",
        desc: "Un raccourci que seuls les habitués connaissent.",
        hint: "Cherche une petite ruelle ou un passage entre deux bâtiments.",
        ar: "orb",
      },
      {
        bearing: 320,
        distance: 160,
        name: "Le point de vue final",
        desc: "Le meilleur endroit pour terminer la balade en beauté.",
        hint: "C'est la dernière étape : profite du moment avant de conclure la balade.",
        ar: "key",
      },
    ],
  },
  {
    id: "adults-medium-spy",
    theme: "spy",
    title: "Chasse à l'Espion",
    emoji: "🕵️",
    audience: "adultes",
    difficultyLabel: "Moyen",
    difficultyStars: 3,
    minAge: "Ados et adultes",
    setting: "Parc, campus ou grand quartier",
    intro:
      "Un agent double a laissé une série de messages codés avant de disparaître. " +
      "Suivez le radar et déchiffrez chaque indice pour reconstituer sa dernière mission.",
    waypoints: [
      {
        bearing: 15,
        distance: 250,
        name: "Point de contact Alpha",
        desc: "Premier lieu de rendez-vous de l'agent.",
        hint: "Indice : compte les lettres du mot 'ESPION' (6) — avance de 6 fois 10 pas.",
        ar: "orb",
      },
      {
        bearing: 95,
        distance: 300,
        name: "La boîte aux lettres morte",
        desc: "Un message aurait été déposé ici, caché à la vue de tous.",
        hint: "Indice : cherche un objet fixe et discret, à hauteur de main.",
        ar: "key",
      },
      {
        bearing: 175,
        distance: 220,
        name: "Le rendez-vous manqué",
        desc: "L'agent ne s'est jamais présenté à ce point.",
        hint: "Indice codé (décalage de 1 lettre) : 'sbuf' → décale chaque lettre d'un cran en arrière.",
        ar: "ghost",
      },
      {
        bearing: 260,
        distance: 350,
        name: "La filature",
        desc: "Quelqu'un a suivi l'agent jusqu'ici.",
        hint: "Indice : le prochain cap est le double du premier (15° x 2), mais utilise celui du radar.",
        ar: "ufo",
      },
      {
        bearing: 340,
        distance: 280,
        name: "Le dossier final",
        desc: "La preuve ultime de la mission de l'agent, enfin récupérée.",
        hint: "Dernier arrêt : la mission est terminée, refermez le dossier.",
        ar: "coin",
      },
    ],
  },
  {
    id: "adults-hard-ghost-protocol",
    theme: "ghost",
    title: "Protocole Fantôme — Signal Zéro",
    emoji: "📡",
    audience: "adultes",
    difficultyLabel: "Difficile",
    difficultyStars: 5,
    minAge: "Adultes",
    setting: "Grand parc, forêt ou zone étendue (1 km+)",
    intro:
      "Un incident a coupé tout le réseau cellulaire de la zone. Les dernières coordonnées " +
      "connues d'une cellule clandestine ont été chiffrées avant la coupure. Sans signal, " +
      "sans data, une seule chose fonctionne encore : les satellites GPS. À vous de reconstituer " +
      "le parcours, point par point, en déchiffrant chaque message intercepté.",
    waypoints: [
      {
        bearing: 10,
        distance: 300,
        name: "Balise Zéro",
        desc: "Dernier signal capté avant la coupure générale.",
        hint: "Message chiffré (César, décalage 3) : 'vljqdo chur' — décale chaque lettre de 3 crans vers l'arrière.",
        ar: "ufo",
      },
      {
        bearing: 75,
        distance: 450,
        name: "Relais abandonné",
        desc: "Une ancienne antenne, désormais silencieuse, marque ce point.",
        hint: "Message chiffré (César, décalage 5) : 'wjqfnx rtwy' à décaler de 5 crans vers l'arrière.",
        ar: "alien",
      },
      {
        bearing: 150,
        distance: 380,
        name: "Le nœud aveugle",
        desc: "Un carrefour où plusieurs pistes se croisent sans indication.",
        hint: "Indice binaire : 01000011 01100001 01110000 = 3 lettres ASCII à convertir (indice : 'Cap').",
        ar: "ghost",
      },
      {
        bearing: 230,
        distance: 500,
        name: "Le bunker silencieux",
        desc: "Une structure discrète, hors de portée de tout capteur réseau.",
        hint: "Additionne les deux premiers caps de ce parcours (10 + 75 = 85), divise par 2 : le résultat est un indice, pas le cap réel.",
        ar: "skull",
      },
      {
        bearing: 300,
        distance: 400,
        name: "Le dernier saut",
        desc: "Le point de rupture avant l'extraction finale.",
        hint: "Message chiffré (César, décalage 1) : 'tbvu gjobm' à décaler de 1 cran vers l'arrière.",
        ar: "alien",
      },
      {
        bearing: 20,
        distance: 250,
        name: "Extraction — Signal rétabli",
        desc: "Mission accomplie. Le protocole fantôme est levé.",
        hint: "Dernier arrêt : c'est ici que le réseau, symboliquement, reprend vie.",
        ar: "orb",
      },
    ],
  },
  {
    id: "kids-easy-circus",
    theme: "circus",
    title: "Le Cirque Magique",
    emoji: "🎪",
    audience: "enfants",
    difficultyLabel: "Facile",
    difficultyStars: 1,
    minAge: "5-8 ans",
    setting: "Jardin, cour ou petit parc",
    intro:
      "Le cirque s'est installé pour une nuit seulement ! Suis les traces des artistes " +
      "pour découvrir toutes leurs cachettes avant qu'ils ne repartent.",
    waypoints: [
      {
        bearing: 40,
        distance: 14,
        name: "Le chapiteau rayé",
        desc: "Le grand chapiteau du cirque est planté ici.",
        hint: "Cherche un endroit qui pourrait ressembler à une grande tente.",
        ar: "dice",
      },
      {
        bearing: 140,
        distance: 20,
        name: "Le fil du funambule",
        desc: "Un funambule s'entraîne sur un fil imaginaire.",
        hint: "Cherche une ligne bien droite au sol, comme une bordure.",
        ar: "coin",
      },
      {
        bearing: 230,
        distance: 16,
        name: "La cage aux lions (vide, ne t'inquiète pas !)",
        desc: "Les lions du cirque font une sieste ailleurs aujourd'hui.",
        hint: "Cherche un endroit clôturé ou entouré.",
        ar: "orb",
      },
      {
        bearing: 320,
        distance: 18,
        name: "Le clown facétieux",
        desc: "Bravo, tu as trouvé la dernière cachette du cirque !",
        hint: "Dernier arrêt : regarde si un objet a l'air amusant ou coloré.",
        ar: "key",
      },
    ],
  },
  {
    id: "kids-medium-explorers",
    theme: "jungle",
    title: "L'Expédition des Explorateurs Perdus",
    emoji: "🗺️",
    audience: "enfants",
    difficultyLabel: "Moyen",
    difficultyStars: 3,
    minAge: "8-11 ans",
    setting: "Parc de quartier",
    intro:
      "Une équipe d'explorateurs a disparu dans la jungle en cherchant un temple oublié. " +
      "Suis leurs traces à travers 5 étapes pour découvrir ce qu'ils ont trouvé.",
    waypoints: [
      {
        bearing: 30,
        distance: 70,
        name: "Le campement de base",
        desc: "Les explorateurs ont établi leur campement ici avant l'aventure.",
        hint: "Cherche un endroit dégagé où l'on pourrait planter une tente.",
        ar: "coin",
      },
      {
        bearing: 110,
        distance: 85,
        name: "Le pont de lianes",
        desc: "Un vieux pont improvisé aurait traversé cet endroit.",
        hint: "Cherche un passage étroit, comme un sentier ou un petit pont.",
        ar: "crystal",
      },
      {
        bearing: 190,
        distance: 65,
        name: "La rivière aux crocodiles (imaginaires)",
        desc: "Attention où vous mettez les pieds, explorateurs !",
        hint: "Reste sur le chemin si le sol est humide par ici.",
        ar: "dice",
      },
      {
        bearing: 260,
        distance: 95,
        name: "Le temple oublié",
        desc: "Une ancienne structure couverte de mousse se dresse ici.",
        hint: "Cherche la structure la plus imposante aux alentours.",
        ar: "skull",
      },
      {
        bearing: 15,
        distance: 55,
        name: "Le trésor de la jungle !",
        desc: "L'expédition touche à sa fin, bravo explorateurs !",
        hint: "Dernier arrêt : regarde bien autour de toi, le trésor est proche.",
        ar: "key",
      },
    ],
  },
  {
    id: "kids-hard-observatory",
    theme: "cosmos",
    title: "Le Code Secret de l'Observatoire",
    emoji: "🔭",
    audience: "enfants",
    difficultyLabel: "Difficile",
    difficultyStars: 4,
    minAge: "11-14 ans",
    setting: "Grand parc ou terrain dégagé, de préférence après le coucher du soleil",
    intro:
      "Un astronome aurait caché une découverte extraordinaire quelque part près de son " +
      "ancien observatoire. Résous les énigmes en plus de suivre le radar pour la retrouver.",
    waypoints: [
      {
        bearing: 5,
        distance: 110,
        name: "La lunette rouillée",
        desc: "Une vieille lunette astronomique pointe vers le ciel ici.",
        hint: "Énigme : compte les lettres du mot \"ÉTOILE\" (6), avance de 6 fois 10 pas dans ce cap.",
        ar: "crystal",
      },
      {
        bearing: 95,
        distance: 150,
        name: "La carte des constellations",
        desc: "Une carte du ciel étoilé est gravée quelque part par ici.",
        hint: "Énigme : la Grande Ourse a 7 étoiles principales ; multiplie par 20 pour avancer.",
        ar: "orb",
      },
      {
        bearing: 170,
        distance: 130,
        name: "Le cadran solaire",
        desc: "Un cadran solaire indique une heure qui n'existe plus.",
        hint: "Énigme : cherche l'endroit où l'ombre serait la plus courte à midi.",
        ar: "ghost",
      },
      {
        bearing: 245,
        distance: 160,
        name: "La météorite gelée",
        desc: "Une pierre étrange, peut-être tombée du ciel, repose ici.",
        hint: "Énigme : Mercure est la 1ère planète, la Terre la 3e ; additionne-les et multiplie par 25.",
        ar: "alien",
      },
      {
        bearing: 320,
        distance: 100,
        name: "L'observatoire secret !",
        desc: "La grande découverte de la nuit t'attend enfin ici.",
        hint: "Dernier arrêt : lève les yeux, l'observatoire est difficile à manquer.",
        ar: "key",
      },
    ],
  },
  {
    id: "adults-easy-market",
    theme: "gourmet",
    title: "Promenade Gourmande du Marché",
    emoji: "🥐",
    audience: "adultes",
    difficultyLabel: "Facile",
    difficultyStars: 2,
    minAge: "Tout public",
    setting: "Quartier commerçant, marché public ou centre-ville",
    intro:
      "Une balade tranquille sur le thème des saveurs locales : quatre arrêts évoquant " +
      "un marché gourmand d'autrefois, à imaginer sur place, sans stress ni chronomètre.",
    waypoints: [
      {
        bearing: 50,
        distance: 160,
        name: "L'étal du fromager",
        desc: "Ici se tenait autrefois un étal réputé pour ses fromages fins.",
        hint: "Cherche un endroit qui pourrait accueillir un kiosque ou un stand.",
        ar: "coin",
      },
      {
        bearing: 130,
        distance: 190,
        name: "Le four à pain communautaire",
        desc: "Le pain frais du quartier sortait de ce four chaque matin.",
        hint: "Cherche une structure ou un bâtiment qui pourrait évoquer un four.",
        ar: "crystal",
      },
      {
        bearing: 210,
        distance: 170,
        name: "La cave à vin oubliée",
        desc: "Une petite cave aurait conservé les meilleurs crus de la région.",
        hint: "Cherche un endroit frais et à l'ombre, peut-être en contrebas.",
        ar: "orb",
      },
      {
        bearing: 300,
        distance: 150,
        name: "La table du marché final",
        desc: "Le repas de fin de marché t'attend à cette dernière étape.",
        hint: "Dernier arrêt : profite du moment, la balade gourmande se termine ici.",
        ar: "key",
      },
    ],
  },
  {
    id: "adults-medium-museum",
    theme: "noir",
    title: "L'Énigme du Musée Disparu",
    emoji: "🖼️",
    audience: "adultes",
    difficultyLabel: "Moyen",
    difficultyStars: 3,
    minAge: "Ados et adultes",
    setting: "Parc, campus ou grand quartier",
    intro:
      "Une œuvre majeure a disparu du musée local durant la nuit, sans un bruit ni une " +
      "seule caméra déclenchée. Suivez le radar et déchiffrez les indices pour retrouver le tableau volé.",
    waypoints: [
      {
        bearing: 20,
        distance: 260,
        name: "Le hall d'entrée silencieux",
        desc: "L'alarme n'a jamais sonné, juste avant la disparition de l'œuvre.",
        hint: "Indice : compte les lettres du mot \"MUSÉE\" (5) — avance de 5 fois 10 pas.",
        ar: "orb",
      },
      {
        bearing: 100,
        distance: 300,
        name: "La galerie aux tableaux vides",
        desc: "Les cadres sont vides, les toiles ont disparu sans un bruit.",
        hint: "Indice : cherche un endroit qui pourrait accueillir des œuvres exposées.",
        ar: "ghost",
      },
      {
        bearing: 180,
        distance: 240,
        name: "Le bureau du conservateur",
        desc: "Des papiers éparpillés suggèrent un départ précipité.",
        hint: "Indice codé (décalage de 2 lettres) : 'xqngwt' à décaler de 2 crans vers l'arrière.",
        ar: "key",
      },
      {
        bearing: 265,
        distance: 320,
        name: "La sortie de secours forcée",
        desc: "Une porte a été forcée durant la nuit du vol.",
        hint: "Indice : le prochain cap est la moitié du premier (20° / 2 = 10°), mais utilise celui du radar.",
        ar: "skull",
      },
      {
        bearing: 340,
        distance: 230,
        name: "L'œuvre retrouvée !",
        desc: "Le tableau disparu est enfin récupéré, intact.",
        hint: "Dernier arrêt : l'enquête est résolue, bravo détective.",
        ar: "crystal",
      },
    ],
  },
  {
    id: "adults-hard-zeroday",
    theme: "terminal",
    title: "Zero Day",
    emoji: "💻",
    audience: "adultes",
    difficultyLabel: "Difficile",
    difficultyStars: 5,
    minAge: "Adultes",
    setting: "Grand parc, forêt ou zone étendue (1 km+)",
    intro:
      "Une faille critique vient d'être découverte dans un système avant une échéance " +
      "cruciale. Votre équipe d'intervention doit retracer, point par point, le chemin de " +
      "l'attaquant à travers la zone avant que la faille ne soit exploitée.",
    waypoints: [
      {
        bearing: 15,
        distance: 320,
        name: "Le point d'entrée",
        desc: "La première trace de compromission a été détectée ici.",
        hint: "Message chiffré (César, décalage 4) : 'mrxvywmsr' à décaler de 4 crans vers l'arrière.",
        ar: "ufo",
      },
      {
        bearing: 85,
        distance: 480,
        name: "Le serveur compromis",
        desc: "Un serveur silencieux tourne encore, mais plus pour son propriétaire légitime.",
        hint: "Message chiffré (César, décalage 6) : 'iusvxusoy' à décaler de 6 crans vers l'arrière.",
        ar: "alien",
      },
      {
        bearing: 160,
        distance: 400,
        name: "Le journal effacé",
        desc: "Quelqu'un a tenté d'effacer ses traces, presque parfaitement.",
        hint: "Indice binaire/hexadécimal : 42 75 67 (hexadécimal) = 3 lettres ASCII à convertir.",
        ar: "ghost",
      },
      {
        bearing: 235,
        distance: 520,
        name: "Le relais dissimulé",
        desc: "Une structure discrète, hors de portée des capteurs habituels.",
        hint: "Additionne les deux premiers caps de ce parcours (15 + 85 = 100), divise par 2 : un indice, pas le cap réel.",
        ar: "skull",
      },
      {
        bearing: 305,
        distance: 380,
        name: "Le correctif d'urgence",
        desc: "La solution existe déjà, il ne reste qu'à la déployer à temps.",
        hint: "Message chiffré (César, décalage 3) : 'fruuhfwli' à décaler de 3 crans vers l'arrière.",
        ar: "orb",
      },
      {
        bearing: 30,
        distance: 260,
        name: "Faille corrigée",
        desc: "Mission accomplie. Le zero-day est désormais connu et corrigé.",
        hint: "Dernier arrêt : la course contre la montre est terminée, bravo à l'équipe.",
        ar: "key",
      },
    ],
  },
];
